# Generated by Django 3.2.5 on 2021-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=40, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Customers', 'Customer'), ('Farmers', 'Farmer')], max_length=20, null=True, verbose_name='User type'),
        ),
    ]
