# Generated by Django 3.2.5 on 2021-07-27 06:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='town_or_city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
