# Generated by Django 3.2.6 on 2021-08-18 08:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.CharField(max_length=80, null=True)),
                ('street_address2', models.CharField(max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40, null=True)),
                ('county', models.CharField(max_length=80, null=True)),
                ('postcode', models.CharField(max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='profiles.address'),
        ),
    ]
