# Generated by Django 3.2.6 on 2021-08-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210818_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
