# Generated by Django 3.2.5 on 2021-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Customers', 'Customer'), ('Farmers', 'Farmer')], default='Customers', max_length=15),
        ),
    ]
