# Generated by Django 3.2.5 on 2021-07-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Customers', 'Customer'), ('Farmers', 'Farmer')], max_length=15),
        ),
    ]
