# Generated by Django 3.2.6 on 2021-08-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
    ]
