# Generated by Django 3.2.5 on 2021-07-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210719_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Customers', 'Customer'), ('Farmers', 'Farmer')], max_length=15, verbose_name='User type'),
        ),
    ]
