# Generated by Django 3.2.5 on 2021-07-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='extra_field',
            field=models.CharField(max_length=20, null=True, verbose_name='Extra Field'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(max_length=20, verbose_name='User type'),
        ),
    ]
