# Generated by Django 3.2.7 on 2023-01-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.CharField(max_length=80, null=True)),
                ('street_address2', models.CharField(max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40, null=True)),
                ('county', models.CharField(max_length=80, null=True)),
                ('postcode', models.CharField(max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_count', models.IntegerField(default=0)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('delivery', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('email', models.EmailField(default=None, max_length=255, null=True, verbose_name='Email address')),
                ('first_name', models.CharField(max_length=40, null=True, verbose_name='First name')),
                ('last_name', models.CharField(max_length=40, null=True, verbose_name='Last name')),
                ('phone_number', models.CharField(default=None, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_bag', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('product_count', models.IntegerField(default=0)),
                ('wh_success', models.BooleanField(default=False)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='checkout.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('farmer_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.farmerorder')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='checkout.order'),
        ),
        migrations.AddConstraint(
            model_name='farmerorder',
            constraint=models.UniqueConstraint(fields=('farmer', 'order'), name='unique_farmer_order'),
        ),
    ]
