# Generated by Django 3.2.6 on 2021-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210823_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
