# Generated by Django 3.2.6 on 2021-08-27 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210827_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='checkout.order'),
        ),
    ]
