# Generated by Django 3.2.6 on 2021-08-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_original_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wh_success',
            field=models.BooleanField(default=False),
        ),
    ]
