# Generated by Django 3.2.6 on 2021-08-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_wh_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='item_distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
