# Generated by Django 3.2.6 on 2021-08-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_item_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='item_distance',
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
