# Generated by Django 3.2.6 on 2021-08-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20210830_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='checkout.order'),
        ),
    ]
