# Generated by Django 3.2.6 on 2021-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_farmerorder_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='farmerorder',
            constraint=models.UniqueConstraint(fields=('farmer', 'order'), name='unique_farmer_order'),
        ),
    ]
